fms/urls.py
#-*- coding: utf-8 -*-
'''
    Author: smallmi
    Blog: http://www.smallmi.com
'''
from django.conf.urls import url,include
from django.contrib import admin
from content import urls,views
from django.conf.urls.static import static
from django.conf import settings
from content import views as content_views
from dashboard import views as dashboard_views

from extra_apps import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from extra_apps.xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    url(r'xadmin/', include(xadmin.site.urls)),
    url(r'^$',dashboard_views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('accounts.urls')),
    url(r'fms/', include('content.urls')),

    url(r'release/', include('release.urls')),
    url(r'cmdb/', include('cmdb.urls')),
    url(r'tasks/', include('tasks.urls')),

    url(r'^type/add$', views.type_add,name='type_add'),
    url(r'^type/del/(?P<id>\d+)$', views.type_del,name='type_del'),

    url(r'^get/email$',views.get_email, name='get_email'),
    url(r'^send/emails$',views.send_mails, name='send_mails'),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^images/upload$', content_views.upload_images, name='upload_images'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

release/urls.py
# -*- coding: UTF-8 -*-
"""skyoms URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from release import views, api

urlpatterns = [

    url(r'^app_list/$', views.app_list, name='app_list'),
    # url(r'^server_add_page/$', views.server_add_page, name='server_add_page'),
    url(r'^app_add/$', views.app_add, name='app_add'),
    # url(r'^server_edit_page/(?P<id>\d+)/$', views.server_edit_page, name='server_edit_page'),
    # # url(r'^server_edit/$', views.server_edit, name='server_edit'),
    url(r'^app_edit/$', views.app_edit, name='app_edit'),
    # # url(r'^server_detail/(?P<id>\d+)/$', views.server_detail, name='server_detail'),
    url(r'^app_delete/$', views.app_delete, name='app_delete'),
    url(r'^search$', api.app_search, name='app_search'),
    #
    #
    # url(r'^server_group/$', views.server_group, name='server_group'),
    # url(r'^group_add/$', views.group_add, name='group_add'),
    # url(r'^group_edit/$', views.group_edit, name='group_edit'),
    # url(r'^group_delete/$', views.group_delete, name='group_delete'),
    # url(r'^group_search$', api.group_search, name='group_search'),
    #
    #
    #
    url(r'^app_platform/$', views.app_platform, name='app_platform'),
    url(r'^platform_add/$', views.platform_add, name='platform_add'),
    url(r'^platform_edit/$', views.platform_edit, name='platform_edit'),
    url(r'^platform_delete/$', views.platform_delete, name='platform_delete'),
    url(r'^platform_search$', api.platform_search, name='platform_search'),
    #
    url(r'^app_server_detail/(?P<id>\d+)$', views.app_server_detail, name='app_server_detail'),
    url(r'^platform_app_detail/(?P<id>\d+)$', views.platform_app_detail, name='platform_app_detail'),
    url(r'^app_server_search$', api.app_server_search, name='app_server_search'),
    url(r'^platform_app_search$', api.platform_app_search, name='platform_app_search'),
    #
    #
    # url(r'^postmachineinfo/$', views.postmachineinfo, name='postmachineinfo'),

]

release/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.db import models
from accounts.models import User


# Create your models here.


class Platform(models.Model):
    # 平台信息
    name = models.CharField(max_length=64, unique=True, verbose_name=u'平台名')
    owner = models.CharField(max_length=64, null=True, verbose_name=u'负责人')
    phone = models.CharField(max_length=64, null=True, verbose_name=u'手机号')
    created_by = models.ForeignKey(User, null=True, verbose_name=u'创建者')
    date_created = models.DateTimeField(auto_now_add=True, null=True, verbose_name=u'创建时间')
    comment = models.TextField(blank=True, verbose_name=u'描述')

    def __unicode__(self):
        return self.name

    __str__ = __unicode__

    class Meta:
        permissions = (
            ("view_platform", ("查看平台")),
            ("add_platform", ("添加平台")),
            ("change_platform", ("编辑平台")),
            ("delete_platform", ("删除平台")),
        )
        default_permissions = ()


class AppProject(models.Model):
    # 应用信息
    java_version = (
        (1, u"version 1.6"),
        (2, u"version 1.7"),
        (3, u"version 1.8"),
    )

    app_name_en = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'英文名称')
    app_name_cn = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'中文名称')
    app_type = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'应用类型')
    platform = models.ForeignKey(Platform, blank=True, null=True, related_name='servers', on_delete=models.SET_NULL,
                                 verbose_name=u'所属平台')

    git_url = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'Git 地址')
    # git_branch = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'Git分支')
    git_properties = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'配置文件')
    java_version = models.IntegerField(choices=java_version, null=True, verbose_name=u'Java版本')

    ctime = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')
    author = models.ForeignKey(User, null=True, verbose_name=u'创建者')
    comment = models.TextField(null=True, blank=True, verbose_name=u'描述')

    def __unicode__(self):
        return '%s（%s）' % (self.app_name_cn, self.app_name_en)

    __str__ = __unicode__

    class Meta:
        permissions = (
            ("view_appProject", ("查看应用信息")),
            ("add_appProject", ("添加应用")),
            ("change_appProject", ("编辑应用")),
            ("delete_appProject", ("删除应用")),
        )
        default_permissions = ()


class ReleasePlan(models.Model):
    # 发布计划
    app = models.ForeignKey(AppProject, blank=True, null=True, related_name='apps', on_delete=models.SET_NULL,
                            verbose_name=u'发布应用')
    git_branch = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'CommitID')
    app_version = models.CharField(max_length=255, null=True, blank=True, verbose_name=u'代码版本')

    plan_status = models.NullBooleanField(default=False, null=True, blank=True, verbose_name=u'发布状态')

    ctime = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')
    author = models.ForeignKey(User, null=True, verbose_name=u'创建者')
    comment = models.TextField(null=True, blank=True, verbose_name=u'描述')

    def __unicode__(self):
        return '%s - %s' % (self.git_branch, self.app_version)

    class Meta:
        permissions = (
            ("view_releasePlan", ("查看发布计划")),
            ("add_releasePlan", ("添加发布计划")),
            ("change_releasePlan", ("编辑发布计划")),
            ("delete_releasePlan", ("删除发布计划")),
        )
        default_permissions = ()

release/views.py
# -*- coding: UTF-8 -*-
import time
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.core.urlresolvers import reverse

from cmdb.forms import ServerForm
from cmdb.models import Server
from controller.public.pagination import *
# from controller.core.ansiblehelp import *
from controller.core.ansible_api import *
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from commons.paginator import paginator
from cmdb.models import *
import json
from django.contrib.auth.decorators import permission_required, login_required
# from permissions import check_permission
# Create your views here.
from controller.public.permissions import check_perms
from release.forms import AppProjectForm
from release.models import Platform

PAGE_SIZE = 10  # 每页显示条数
current_page_total = 10  # 分页下标


@login_required
def index(request):
    user = request.user
    if user.is_superuser:
        role = '超级管理员'
    elif user.is_anonymous():
        role = '匿名用户'
    else:
        role = '普通用户'
    request.role = role
    return render_to_response('base/index.html', {'request': request})

# def time_count(content, start_time, end_time):
#
#     start_time = time.strptime(str(start_time).split('+')[0], "%Y-%m-%d %H:%M:%S")
#     end_time = time.strptime(
#         str(end_time).split('+')[0], "%Y-%m-%d %H:%M:%S")
#     timestamp = int(time.mktime(end_time)) - int(time.mktime(start_time))
#
#     setattr(content, 'time', str(timestamp // 3600) + '小时' + str(timestamp % 3600 // 60) + '分')

@login_required
@permission_required('release.view_appProject', raise_exception=True)
def app_list(request):
    data = {}
    # if request.method == "POST":
    #     form = IDCForm(request.POST)
    # else:

    form = AppProjectForm()
    appProject = AppProject.objects.annotate(average_server=Count('app')).order_by('id')
    platforms = Platform.objects.values_list('id', 'name')
    java_version_list = [(0, '----------'), (1, 'version 1.6'), (2, 'version 1.7'), (3, 'version 1.8')]

    data = paginator(request, appProject)

    request.breadcrumbs((('首页', '/'), ('应用列表', reverse('app_list'))))

    data['form'] = form
    data['platforms'] = json.dumps([(i[0], i[1]) for i in platforms])
    data['java_version_list'] = json.dumps(java_version_list)

    return render_to_response('release/app.html', data)


@login_required
@permission_required('cmdb.view_servergroup', raise_exception=True)
def server_group(request):
    data = {}
    # group = ServerGroup.objects.order_by('id')
    group = ServerGroup.objects.annotate(average_server=Count('servers')).order_by('id')
    data = paginator(request, group)
    request.breadcrumbs((('首页', '/'), ('资产组列表', reverse('server_group'))))

    return render_to_response('cmdb/group.html', data)


@login_required
@permission_required('release.view_platform', raise_exception=True)
def app_platform(request):

    data = {}
    platform = Platform.objects.annotate(average_app=Count('servers')).order_by('id')
    data = paginator(request, platform)
    request.breadcrumbs((('首页', '/'), ('平台列表', reverse('app_platform'))))
    if request.method != "POST":
        return render_to_response('release/platform.html', data)
    else:
        return render_to_response('release/app.html', data)


def server_add_page(request):
    # 新增机器页面
    return render_to_response('cmdb/server_add.html', locals(), context_instance=RequestContext(request))


@login_required
# @permission_required('cmdb.add_server', raise_exception=True)
def app_add(request):
    # 新增机器
    error = ""
    if check_perms(request, 'release.add_appProject', raise_exception=True):
        if request.method == "POST":
            # groups = request.POST.getlist('groups')
            new_app_name_en = request.POST.get('app_name_en')
            appProject = AppProject.objects.filter(app_name_en=new_app_name_en)

            form = AppProjectForm(request.POST)

            if appProject:
                error = u"该应用已存在!"
            elif new_app_name_en == '':
                error = u"你闲的蛋疼么？字都懒得打！"
            else:
                if form.is_valid():
                    appProject = form.save(commit=False)
                    appProject.author = request.user
                    appProject.save()
                    # response.write(json.dumps(u'成功'))
                    return HttpResponseRedirect(reverse('app_list'))
    else:
        error = u'您没有权限操作@^@，请联系管理员！'

    return render(request, 'error.html', {'request': request, 'error': error})


@login_required
# @permission_required('cmdb.add_servergroup', raise_exception=True)
def group_add(request):
    # 新增资产组
    response = HttpResponse()

    if check_perms(request, 'cmdb.add_servergroup', raise_exception=True):
        if request.method == "POST":
            user = request.user
            data = json.loads(request.POST.get('data', ''))

            groupName = data['group_name']

            group = ServerGroup.objects.filter(name=groupName)

            if group:
                response.write(json.dumps(u'尼玛，重复了！'))
            elif len(groupName) == 0:
                response.write(json.dumps(u'你闲的蛋疼么？字都懒得打！'))
            else:
                group = ServerGroup()
                group.created_by_id = user.id
                group.name = groupName
                group.comment = data['group_comment']
                try:
                    group.save()
                except:
                    response.write(json.dumps(u'异常'))
                else:
                    response.write(json.dumps(u'成功'))

        else:
            pass
    else:
        response.write(json.dumps(u'您没有权限操作@^@，请联系管理员！'))

    return response


@login_required
# @permission_required('cmdb.add_idc', raise_exception=True)
def platform_add(request):
    # 新增IDC
    response = HttpResponse()

    if check_perms(request, 'release.add_platform', raise_exception=True):
        error = ""
        if request.method == "POST":
            user = request.user
            data = json.loads(request.POST.get('data', ''))

            new_platform = data['add_platform']
            platform = Platform.objects.filter(name=new_platform)

            if platform:
                response.write(json.dumps(u'尼玛，重复了！'))
            elif len(new_platform) == 0:
                response.write(json.dumps(u'你闲的蛋疼么？字都懒得打！'))
            else:
                try:
                    platform = Platform()
                    platform.created_by_id = user.id
                    platform.name = new_platform
                    platform.owner = data['add_owner']
                    platform.phone = data['add_phone']
                    platform.comment = data['add_comment']
                    platform.save()
                except:
                    response.write(json.dumps(u'异常'))
                else:
                    response.write(json.dumps(u'成功'))

        else:
            pass
    else:
        response.write(json.dumps(u'您没有权限操作@^@，请联系管理员！'))

    return response


def server_edit_page(request, id):
    pass
    # 编辑机器页面
    # server = Server.objects.get(pk=id)
    # return render_to_response('cmdb/server_edit.html', locals(), context_instance=RequestContext(request))


@login_required
# @permission_required('cmdb.change_server', raise_exception=True)
def app_edit(request):
    # 编辑机器
    response = HttpResponse()
    if check_perms(request, 'release.change_appProject', raise_exception=True):
        data = json.loads(request.POST.get('data', ''))

        app_id = data['app_id']
        app_name_cn = data['app_name_cn']
        app_name_en = data['app_name_en']
        app_type = data['app_type']
        git_url = data['git_url']
        git_properties = data['git_properties']
        java_version = data['edit_java_version']
        platform = data['edit_platform']

        appProject = AppProject.objects.get(pk=app_id)
        appProject.app_name_cn = app_name_cn
        appProject.app_name_en = app_name_en
        appProject.app_type = app_type
        appProject.git_url = git_url
        appProject.git_properties = git_properties
        appProject.java_version = java_version
        appProject.platform_id = platform

        appProject.save()

        response.write(json.dumps(u'成功'))
    else:
        response.write(json.dumps(u'您没有权限操作@^@，请联系管理员！'))

    return response


@login_required
# @permission_required('cmdb.change_servergroup', raise_exception=True)
def group_edit(request):
    # 编辑机器
    response = HttpResponse()
    if check_perms(request, 'cmdb.change_servergroup', raise_exception=True):
        data = json.loads(request.POST.get('data', ''))

        id = data['id']
        group_name = data['group_name']
        group_comment = data['group_comment']

        group = ServerGroup.objects.get(pk=id)
        group.name = group_name
        group.comment = group_comment
        group.save()

        response.write(json.dumps(u'成功'))
    else:
        response.write(json.dumps(u'您没有权限操作@^@，请联系管理员！'))

    return response


@login_required
# @permission_required('cmdb.change_idc', raise_exception=True)
def platform_edit(request):

    response = HttpResponse()

    if check_perms(request, 'release.change_platform', raise_exception=True):
        data = json.loads(request.POST.get('data', ''))

        id = data['id']

        platform = Platform.objects.get(pk=id)
        platform.name = data['platform']
        platform.owner = data['owner']
        platform.phone = data['phone']
        platform.comment = data['comment']
        try:
            platform.save()
        except:
            response.write(json.dumps(u'失败'))
        else:
            response.write(json.dumps(u'成功'))
    else:
        response.write(json.dumps(u'您没有权限操作@^@，请联系管理员！'))

    return response


@login_required

templates/release/app_table.html
{% for i in content %}
    <tr class="gradeA odd" role="row">
        <td class="sorting_1">{{ forloop.counter }}</td>
        <td class="center"><a href="/release/app_server_detail/{{ i.id }}">{{ i.app_name_cn}}（{{ i.app_name_en }}）</a></td>
        <td class="center">{{ i.average_server }}</td>
        <td class="center">{{ i.app_type }}</td>
        <td class="center">{{ i.platform }}</td>
        <td class="center">{{ i.java_version }}</td>
        {% if i.java_version != 0 %}
            <td class="center">{{ i.get_java_version_display }}</td>
        {% else %}
            <td class="center">未使用</td>
        {% endif %}
        <td class="center">{{ i.author.fullname }}</td>
        <td class="center">{{ i.ctime }}</td>

        <td class="center">
            <button data-row="{{ i.id }}|{{ i.app_name_cn }}|{{ i.app_name_en }}|{{ i.app_type }}|{{ i.git_url }}|{{ i.git_properties }}|{{ i.platform_id }}|{{ i.java_version }}" class="btn btn-xs btn-warning btn-edit" data-toggle="modal" data-target="#editInfoModal">变更</button>
            <a class="btn btn-xs btn-danger" id="app_delete_{{i.id}}">删除</a>
        </td>
    </tr>


    <script type="text/javascript">
        /**
         * 编辑表单
         * **/

        $('.btn-edit').on('click', function (event) {
            var platforms ={{ platforms | safe}};
            var java_version_list = {{ java_version_list | safe}};

            var btn = $(event.target);
            var row = btn.data('row').split('|');

            $('#app_id').val(row[0]);
            $('#app_name_cn').val(row[1]);
            $('#app_name_en').val(row[2]);
            $('#app_type').val(row[3]);
            $('#git_url').val(row[4]);
            $('#git_properties').val(row[5]);

            $('#edit_platform').empty();
            $('#edit_java_version').empty();

            var platform = row[6]
            var java_version = row[7];

            jQuery.each(java_version_list,function (key, value) {
                var t = jQuery("<option value=" + value[0]+">" + value[1] + "</option>");
               if(value[0] == java_version){
                    t.attr("selected","selected");
               }
                $('#edit_java_version').append(t);
            });

            $('#edit_platform').append("<option value=''>----------</option>");
            jQuery.each(platforms, function (key, value) {
                var t = jQuery("<option value=" + value[0] + ">" + value[1] + "</option>");
                if (value[0] == platform) {
                    t.attr("selected", "selected");
                }
                $('#edit_platform').append(t);
            });


            row_group = row[5].split(',');
            if (groups != "") {
                $.each(groups, function (key, value) {
                    var obj = document.getElementById("edit_groups");
                    var op = new Option(value[1], value[0])
                    if (row_group.contains(value[1])) {
                        op.selected = true;
                    }
                    obj.add(op);
                });
            } else if (groups == "") {

                $.each(groups, function (key, value) {
                    var obj = document.getElementById("edit_groups");
                    var op = new Option(value[1], value[0])
                    obj.add(op);
                });
            }
            resetChosen();
        })
    </script>


    <script>
        /*
        *删除机器信息
        */
        $("table tbody tr td a[id^='app_delete']").click(function () {
            var id_val = $(this).attr('id');
            var id = id_val.split('_')[2];
            var data = {"id": id};
            data = JSON.stringify(data);
            var url = "/release/app_delete/";

            var index = layer.confirm('确定删除吗？', {
                btn: ['确定', '取消'] //按钮
            }, function () {
                $.post(url, {data: data}, function (msg) {
                    ajax_callback(msg);
                });
            }, function () {
                layer.close(index)
            });
        });


        /*
        *保存编辑服务器信息数据
        */
        $('#editSave').click(function () {
            var app_id = $("#app_id").val();
            var app_name_cn = $("#app_name_cn").val();
            var app_name_en = $("#app_name_en").val();
            var app_type = $("#app_type").val();
            var git_url = $("#git_url").val();
            var git_properties = $("#git_properties").val();
            var edit_java_version = $("#edit_java_version").find("option:selected").val();
            var edit_platform = $("#edit_platform").find("option:selected").val();
            data = {
                "app_id": app_id,
                "app_name_cn": app_name_cn,
                "app_name_en": app_name_en,
                "app_type": app_type,
                "git_url": git_url,
                "git_properties": git_properties,
                "edit_java_version": edit_java_version,
                "edit_platform": edit_platform
            };
            data = JSON.stringify(data);
            var url = "/release/app_edit/";

            $.post(url, {data: data}, function (msg) {
                $('#editInfoModal').modal('hide')
                ajax_callback(msg);
            });
        });

        /*
        *ajax get callback
        */
        function ajax_callback(msg) {
            var msg = $.parseJSON(msg);
            var index = layer.alert(msg, { //layer控件提示信息
                skin: 'layui-layer-molv' //样式类名
            }, function () {
                if (msg == '成功') {
                    window.location = "/release/app_list/";
                }
                else if (msg == '失败') {
                    window.location = "/release/app_list/";
                }
                    {#        else if (msg == '无权限操作'){#}
                    {#            window.location="/cmdb/server_list/";#}
                    {#        }#}
                else {
                    layer.close(index)
                }
            });
        }

    </script>
{% endfor %}

templates/release/platform_app_table.html
{% load accounts_tag %}
{% for i in content %}
    <tr class="gradeA odd" role="row">
        <td class="sorting_1">{{ forloop.counter }}</td>
        <td class="center">{{ i.app_name_cn}}（{{ i.app_name_en }}）</td>
        <td class="center">{{ i.app_type }}</td>
        <td class="center">{{ i.java_version }}</td>
        {% if i.java_version != 0 %}
            <td class="center">{{ i.get_java_version_display }}</td>
        {% else %}
            <td class="center">未使用</td>
        {% endif %}
        <td class="center">{{ i.ctime }}</td>

        <td class="center">
            <button data-row="{{ i.id }}|{{ i.app_name_cn }}|{{ i.app_name_en }}|{{ i.app_type }}|{{ i.git_url }}|{{ i.git_properties }}|{{ i.platform_id }}|{{ i.java_version }}" class="btn btn-xs btn-warning btn-edit" data-toggle="modal" data-target="#editInfoModal">变更</button>
            <a class="btn btn-xs btn-danger" id="app_delete_{{i.id}}">删除</a>
        </td>
    </tr>


    <script type="text/javascript">

        /**
         * 编辑表单
         * **/

        $('.btn-edit').on('click', function (event) {

            var platforms ={{ platforms | safe}};
            var java_version_list = {{ java_version_list | safe}};

            var btn = $(event.target);
            var row = btn.data('row').split('|');

            $('#app_id').val(row[0]);
            $('#app_name_cn').val(row[1]);
            $('#app_name_en').val(row[2]);
            $('#app_type').val(row[3]);
            $('#git_url').val(row[4]);
            $('#git_properties').val(row[5]);

            $('#edit_platform').empty();
            $('#edit_java_version').empty();

            var platform = row[6]
            var java_version = row[7];

            jQuery.each(java_version_list,function (key, value) {
                var t = jQuery("<option value=" + value[0]+">" + value[1] + "</option>");
               if(value[0] == java_version){
                    t.attr("selected","selected");
               }
                $('#edit_java_version').append(t);
            });

            $('#edit_platform').append("<option value=''>----------</option>");
            jQuery.each(platforms, function (key, value) {
                var t = jQuery("<option value=" + value[0] + ">" + value[1] + "</option>");
                if (value[0] == platform) {
                    t.attr("selected", "selected");
                }
                $('#edit_platform').append(t);
            });

        })
    </script>

    <script>
        /*
        *删除机器信息
        */
        $("table tbody tr td a[id^='app_delete']").click(function () {
            var id_val = $(this).attr('id');
            var id = id_val.split('_')[2];
            var data = {"id": id};
            data = JSON.stringify(data);
            var url = "/release/app_delete/";

            var index = layer.confirm('确定删除吗？', {
                btn: ['确定', '取消'] //按钮
            }, function () {
                $.post(url, {data: data}, function (msg) {
                    update_ajax_callback(msg, {{ platformId }});
                });
            }, function () {
                layer.close(index)
            });
        });


         /*
        *保存编辑服务器信息数据
        */
        $('#editSave').click(function () {
            var app_id = $("#app_id").val();
            var app_name_cn = $("#app_name_cn").val();
            var app_name_en = $("#app_name_en").val();
            var app_type = $("#app_type").val();
            var git_url = $("#git_url").val();
            var git_properties = $("#git_properties").val();
            var edit_java_version = $("#edit_java_version").find("option:selected").val();
            var edit_platform = $("#edit_platform").find("option:selected").val();
            data = {
                "app_id": app_id,
                "app_name_cn": app_name_cn,
                "app_name_en": app_name_en,
                "app_type": app_type,
                "git_url": git_url,
                "git_properties": git_properties,
                "edit_java_version": edit_java_version,
                "edit_platform": edit_platform
            };
            data = JSON.stringify(data);
            var url = "/release/app_edit/";

            $.post(url, {data: data}, function (msg) {
                $('#editInfoModal').modal('hide')
                update_ajax_callback(msg, {{ platformId }});
            });
        });

        /*
*ajax get callback
*/
        function update_ajax_callback(msg, id) {
            var msg = $.parseJSON(msg);
            var index = layer.alert(msg, { //layer控件提示信息
                skin: 'layui-layer-molv' //样式类名
            }, function () {
                if (msg == '成功') {
                    window.location = "/release/platform_app_detail/" + id;
                }
                else if (msg == '失败') {
                    window.location = "/release/platform_app_detail/" + id;
                }
                    {#        else if (msg == '无权限操作'){#}
                    {#            window.location="/cmdb/server_list/";#}
                    {#        }#}
                else {
                    layer.close(index)
                }
            });
        }

    </script>
{% endfor %}